modLoader="javafml"
loaderVersion="[${fml},)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/SimplyTools/issues"

[[mods]]
modId="simplytools"
version="${version}"
displayName="Simply Tools"
updateJSONURL="https://assets.melanx.de/updates/simply-tools.json"
authors="MelanX"
description="""
Hammers and Excavators to mine 3x3 areas
Install MoreVanillaTools for more different materials
Install MoreVanillaLib for special effects ingame
"""

[[dependencies.simplytools]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplytools]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplytools]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.simplytools]]
    modId="morevanillatools"
    mandatory=false
    versionRange="[1.20.1-6.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.simplytools]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[1.20.1-5.0.1,)"
    ordering="AFTER"
    side="BOTH"
