modLoader="javafml"
loaderVersion="[4,)"
license="${mod.license}"
issueTrackerURL="${mod.issue_url}"

[[mods]]
modId="${mod.modid}"
version="${mod.version}"
displayName="Simply Tools"
displayURL="${mod.source_url}"
updateJSONURL="https://assets.melanx.de/updates/simply-tools.json"
authors="MelanX"
description="""
Hammers and Excavators to mine 3x3 areas
Install MoreVanillaTools for more different materials
Install MoreVanillaLib for special effects ingame
"""

[[dependencies.${mod.modid}]]
    modId="neoforge"
    mandatory=true
    versionRange="[${mod.neoforge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod.minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="libx"
    mandatory=true
    versionRange="[1.21.1-6.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="morevanillatools"
    mandatory=false
    versionRange="[21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod.modid}]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[21.1,)"
    ordering="AFTER"
    side="BOTH"
